name: Main

on:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '0 0 1,5,10,15,20,25 * *'

# jobs:

#   build-publish-trigger:
#     runs-on: ubuntu-latest
#     env: 
#       DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
#       DOCKER_USER: ${{ secrets.DOCKER_USER }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Build image, test it, push it dockerhub, notify dependents
#         run: ./pipe_build_up_test.sh
  
jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

  build-publish:
    needs: [pre-build]
    permissions:
      id-token: write
      contents: write
    uses: cyber-dojo/reusable-actions-workflows/.github/workflows/kosli_build_test_push_dockerhub.yml@main
    secrets:
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    with:
      BUILD_COMMAND: pipe_build_up_test.sh
      KOSLI_FLOW: java